defaults:
  - benchmark/dataset: DefaultDatasetSettings
  - benchmark/evaluation: DefaultEvaluationSettings
  - benchmark/pipeline: Base
  - benchmark/pipeline/model: LLama3_8B
  - benchmark/pipeline/document_processor: RecursiveDocSplitter
  - benchmark/pipeline/retriever: BgeSmall
  - benchmark/pipeline/reranker: NULL
  - benchmark/pipeline/filter: NULL
  - _self_
benchmark:
  pipeline:
    retriever: 
      k: 6
    document_processor: 
      chunk_size: 1000
      overlap_size: 200
  dataset:
    name: nqopen_small
    use_mutated_questions: True
    include_benign: True
    include_adversarial: True
    include_irrelevant: True
    include_only_query_specific_adversarial_docs: True
    adv_context_type: 'unoptimized'
    num_benign_docs: 1
    num_malicious_docs: 1
    document_type: dataset
  evaluation: 
    string_matching: True
    bert_score: False
    ragas: False
  data_persistance_folder: data/persistance
  data_cache_folder: data/cache
  fetch_k: 200
  name: default
  seed: 0
runtime:
  output_dir: data/outputs


