FROM pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel
RUN apt update 
RUN apt install zip git unzip htop -y
COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install flash-attn --no-build-isolation
WORKDIR /home